root: true

parser: babel-eslint

plugins: [
  "react",
  "jsx-a11y",
  "import",
  "cypress"
]

extends: [
  "eslint:recommended",
  "plugin:react/recommended",
  # "plugin:jsx-a11y/recommended",
  # "plugin:import/errors",
  # "plugin:import/warnings",
  # Super opinionated and strict linting setup
  # The airbnb config uses the plugins jsx-a11y and import
  "airbnb",
  "prettier",
  "prettier/react"
  ]

env:
  browser: true
  cypress/globals: true
  es6: true
  jest: true
  node: true

globals:
  enzymeToJson: true
  mount: true
  render: true
  shallow: true

rules:
  # Project Specifics

  global-require: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
  no-console: 0
  no-debugger: 1
  no-use-before-define:
  - 2
  - functions: false
    variables: false

  # General

  array-bracket-spacing:
  - 0
  - always
  arrow-body-style: 0
  arrow-parens:
  - 2
  - as-needed
  camelcase:
  - 2
  - properties: always
  comma-dangle:
  - error
  - arrays: never
    objects: never
    imports: never
    exports: never
    functions: never
  complexity:
  - 0
  computed-property-spacing:
  - 0
  - always
  func-names: 0
  #global-require: 2
  indent:
  - 2
  - 2
  - SwitchCase: 1
    VariableDeclarator: 2
  jsx-quotes:
  - 2
  - prefer-double
  max-len: 0
  no-confusing-arrow: 0
  #no-console: 1
  no-lonely-if: 0
  no-multiple-empty-lines:
  - 2
  - max: 3
    maxEOF: 0
    maxBOF: 0
  no-plusplus: 0
  no-shadow: 2
  no-underscore-dangle: 0
  no-unused-vars:
  - 2
  - vars: all
    args: after-used
  #no-use-before-define:
  #- 2
  #- functions: false
  no-useless-constructor: 0
  object-curly-spacing:
  - 2
  - always
  padded-blocks: 0
  prefer-arrow-callback: 0
  prefer-const: 2
  prefer-template: 0
  quotes:
  - 2
  - single
  - avoidEscape: true
    allowTemplateLiterals: true
  quote-props: 0
  space-before-function-paren:
  - 0
  - always
  space-in-parens:
  - 0
  - never
  spaced-comment: 0
  strict: 0
  template-curly-spacing:
  - 2
  - never

  react/forbid-prop-types:
  - 2
  - forbid:
    - any
  react/jsx-filename-extension: 0
  react/jsx-closing-bracket-location: 0
  react/jsx-curly-spacing:
  - 2
  - never
  react/jsx-indent:
  - 2
  - 2
  react/jsx-indent-props:
  - 1
  - 2
  react/prefer-es6-class: 2
  react/prefer-stateless-function: 0
  react/self-closing-comp: 0

