language: node_js
node_js:
  #  - "6"
  #  - "7"
  - '10.15.1'

#env:
#  global:
#    - BUILD_TIMEOUT=10000

before_install: rm -rf node_modules

install: yarn install

script: yarn build:ci
#after_success: ./node_modules/gh-pages/bin/gh-pages --repo https://$GITHUB_TOKEN@github.com/john-d-pelingo/react-key-codes.git -d build

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard: https://docs.travis-ci.com/user/deployment/pages/
#  local_dir: build
#  on:
#    branch: master
