language: node_js
node_js:
  #  - "6"
  #  - "7"
  - '12.22.6'

#env:
#  global:
#    - BUILD_TIMEOUT=10000

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

before_install: rm -rf node_modules

install: yarn install

script: yarn build:ci
#after_success: ./node_modules/gh-pages/bin/gh-pages --repo https://$GITHUB_TOKEN@github.com/john-d-pelingo/react-key-codes.git -d build

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard: https://docs.travis-ci.com/user/deployment/pages/
#  local_dir: build
#  on:
#    branch: master
