# Good template: https://github.com/gruntjs/grunt/blob/master/appveyor.yml

# Fix line endings on Windows
#init:
#  - git config --global core.autocrlf true

# Test against the latest version of this Node.js version.
environment:
  nodejs_version: '10.15.1'

# What combinations to test.
#environment:
#  matrix:
#    - nodejs_version: "5"
#    - nodejs_version: "6"
#    - nodejs_version: "7"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn install

# Don't actually build.
build: off

branches:
  only:
    - master

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version && yarn --version
  # Run all tests.
  - yarn build:ci
